[plugin-beancount-nvim]
src.git = "https://github.com/polarmutex/beancount.nvim"
fetch.github = "polarmutex/beancount.nvim"
git.leaveDotGit = true

[plugin-cmp-buffer]
src.git = "https://github.com/hrsh7th/cmp-buffer"
fetch.github = "hrsh7th/cmp-buffer"
git.leaveDotGit = true

[plugin-cmp-calc]
src.git = "https://github.com/hrsh7th/cmp-calc"
fetch.github = "hrsh7th/cmp-calc"
git.leaveDotGit = true

[plugin-cmp-cmdline]
src.git = "https://github.com/hrsh7th/cmp-cmdline"
fetch.github = "hrsh7th/cmp-cmdline"
git.leaveDotGit = true

[plugin-cmp-dap]
src.git = "https://github.com/rcarriga/cmp-dap"
fetch.github = "rcarriga/cmp-dap"
git.leaveDotGit = true

[plugin-cmp-emoji]
src.git = "https://github.com/hrsh7th/cmp-emoji"
fetch.github = "hrsh7th/cmp-emoji"
git.leaveDotGit = true

[plugin-cmp-nvim-lsp]
src.git = "https://github.com/hrsh7th/cmp-nvim-lsp"
fetch.github = "hrsh7th/cmp-nvim-lsp"
git.leaveDotGit = true

[plugin-cmp-nvim-lsp-signature-help]
src.git = "https://github.com/hrsh7th/cmp-nvim-lsp-signature-help"
fetch.github = "hrsh7th/cmp-nvim-lsp-signature-help"
git.leaveDotGit = true

[plugin-cmp-path]
src.git = "https://github.com/hrsh7th/cmp-path"
fetch.github = "hrsh7th/cmp-path"
git.leaveDotGit = true

[plugin-cmp-omni]
src.git = "https://github.com/hrsh7th/cmp-omni"
fetch.github = "hrsh7th/cmp-omni"
git.leaveDotGit = true

[plugin-crates-nvim]
src.git = "https://github.com/Saecki/crates.nvim"
fetch.github = "Saecki/crates.nvim"
git.leaveDotGit = true

[plugin-diffview-nvim]
src.git = "https://github.com/sindrets/diffview.nvim"
fetch.github = "sindrets/diffview.nvim"
git.leaveDotGit = true

[plugin-gitsigns-nvim]
src.git = "https://github.com/lewis6991/gitsigns.nvim"
fetch.github = "lewis6991/gitsigns.nvim"
git.leaveDotGit = true

[plugin-gitworktree-nvim]
src.git = "https://github.com/ThePrimeagen/git-worktree.nvim"
fetch.github = "ThePrimeagen/git-worktree.nvim"
git.leaveDotGit = true

[plugin-harpoon]
src.git = "https://github.com/ThePrimeagen/harpoon"
fetch.github = "ThePrimeagen/harpoon"
git.leaveDotGit = true

[plugin-heirline-nvim]
src.git = "https://github.com/rebelot/heirline.nvim"
fetch.github = "rebelot/heirline.nvim"
git.leaveDotGit = true

[plugin-lazy-nvim]
src.git = "https://github.com/folke/lazy.nvim"
fetch.github = "folke/lazy.nvim"
git.leaveDotGit = true

[plugin-lspformat-nvim]
src.git = "https://github.com/lukas-reineke/lsp-format.nvim"
fetch.github = "lukas-reineke/lsp-format.nvim"
git.leaveDotGit = true

[plugin-lspkind-nvim]
src.git = "https://github.com/onsails/lspkind.nvim"
fetch.github = "onsails/lspkind.nvim"
git.leaveDotGit = true

[plugin-neodev-nvim]
src.git = "https://github.com/folke/neodev.nvim"
fetch.github = "folke/neodev.nvim"
git.leaveDotGit = true

[plugin-neogit]
src.git = "https://github.com/TimUntersberger/neogit"
fetch.github = "TimUntersberger/neogit"
git.leaveDotGit = true

[plugin-noice-nvim]
src.git = "https://github.com/folke/noice.nvim"
fetch.github = "folke/noice.nvim"
git.leaveDotGit = true

[plugin-nui-nvim]
src.git = "https://github.com/MunifTanjim/nui.nvim"
fetch.github = "MunifTanjim/nui.nvim"
git.leaveDotGit = true

[plugin-null-ls-nvim]
src.git = "https://github.com/jose-elias-alvarez/null-ls.nvim"
fetch.github = "jose-elias-alvarez/null-ls.nvim"
git.leaveDotGit = true

[plugin-nvim-colorizer]
src.git = "https://github.com/norcalli/nvim-colorizer.lua"
fetch.github = "norcalli/nvim-colorizer.lua"
git.leaveDotGit = true

[plugin-nvim-cmp]
src.git = "https://github.com/hrsh7th/nvim-cmp"
fetch.github = "hrsh7th/nvim-cmp"
git.leaveDotGit = true

[plugin-nvim-dap]
src.git = "https://github.com/mfussenegger/nvim-dap"
fetch.github = "mfussenegger/nvim-dap"
git.leaveDotGit = true

[plugin-nvim-dap-python]
src.git = "https://github.com/mfussenegger/nvim-dap-python"
fetch.github = "mfussenegger/nvim-dap-python"
git.leaveDotGit = true

[plugin-nvim-dap-ui]
src.git = "https://github.com/rcarriga/nvim-dap-ui"
fetch.github = "rcarriga/nvim-dap-ui"
git.leaveDotGit = true

[plugin-nvim-dap-virtual-text]
src.git = "https://github.com/theHamsta/nvim-dap-virtual-text"
fetch.github = "theHamsta/nvim-dap-virtual-text"
git.leaveDotGit = true

[plugin-nvim-lspconfig]
src.git = "https://github.com/neovim/nvim-lspconfig"
fetch.github = "neovim/nvim-lspconfig"
git.leaveDotGit = true

[plugin-nvim-treesitter]
src.git = "https://github.com/nvim-treesitter/nvim-treesitter"
fetch.github = "nvim-treesitter/nvim-treesitter"
git.leaveDotGit = true

[plugin-nvim-treesitter-playground]
src.git = "https://github.com/nvim-treesitter/playground"
fetch.github = "nvim-treesitter/playground"
git.leaveDotGit = true

[plugin-one-small-step-for-vimkind]
src.git = "https://github.com/jbyuki/one-small-step-for-vimkind"
fetch.github = "jbyuki/one-small-step-for-vimkind"
git.leaveDotGit = true

[plugin-plenary-nvim]
src.git = "https://github.com/nvim-lua/plenary.nvim"
fetch.github = "nvim-lua/plenary.nvim"
git.leaveDotGit = true

[plugin-rust-tools-nvim]
src.git = "https://github.com/simrat39/rust-tools.nvim"
fetch.github = "simrat39/rust-tools.nvim"
git.leaveDotGit = true

[plugin-telescope-nvim]
src.git = "https://github.com/nvim-telescope/telescope.nvim"
fetch.github = "nvim-telescope/telescope.nvim"
git.leaveDotGit = true

[plugin-tokyonight-nvim]
src.git = "https://github.com/folke/tokyonight.nvim"
fetch.github = "folke/tokyonight.nvim"
git.leaveDotGit = true

[plugin-vim-be-good]
src.git = "https://github.com/ThePrimeagen/vim-be-good"
fetch.github = "ThePrimeagen/vim-be-good"
git.leaveDotGit = true

[plugin-nvim-web-devicons]
src.git = "https://github.com/nvim-tree/nvim-web-devicons"
fetch.github = "nvim-tree/nvim-web-devicons"
git.leaveDotGit = true

[tree-sitter-beancount]
src.git = "https://github.com/polarmutex/tree-sitter-beancount"
src.branch = "devel"
fetch.github = "polarmutex/tree-sitter-beancount"

