name: Automatic Rebase
on:
  push:
    branches-ignore:
      # Ignore branches automatically created by github-rebase
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**
  pull_request:
    types:
      - labeled
jobs:
  auto-rebase:
    name: AutoRebase
    runs-on: ubuntu-latest
    steps:
      - uses: Label305/AutoRebase@v0.1
        with:
          github_token: ${{ secrets.PAT }}
