# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: nix-check

on:
  pull_request:

jobs:
  check_flake:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://polarmutex.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= polarmutex.cachix.org-1:kUFH4ftZAlTrKlfFaKfdhKElKnvynBMOg77XRL2pc08=
      - uses: cachix/cachix-action@v14
        with:
          name: polarmutex
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build everything
        run: |
          nix flake check -L --accept-flake-config
