# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: update-flakes
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 5"

jobs:
  nvfetcher_matrix:
    name: Generate nvfetcher update matrix
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.matrix.outputs.plugins }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v25
      with:
        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://polarmutex.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= polarmutex.cachix.org-1:kUFH4ftZAlTrKlfFaKfdhKElKnvynBMOg77XRL2pc08=
    - name: Generate matrix
      id: matrix
      run: |
        set -ex
        nix profile install .#jq .#fd
        plugins="$(fd 'nvfetcher.toml' pkgs/plugins --exec dirname {} \; | xargs basename -a | jq -ncR '[inputs]')"
        echo "plugins=$plugins" >> $GITHUB_OUTPUT

  nvfetcher_update:
    runs-on: ubuntu-latest
    needs: [nvfetcher_matrix]
    if: ${{ needs.nvfetcher_matrix.outputs.plugins != '[]' && needs.nvfetcher_matrix.outputs.plugins != '' }}
    strategy:
      fail-fast: false
      matrix:
        plugin: ${{ fromJson(needs.nvfetcher_matrix.outputs.plugins )}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v25
      with:
        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://polarmutex.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= polarmutex.cachix.org-1:kUFH4ftZAlTrKlfFaKfdhKElKnvynBMOg77XRL2pc08=
    - name: Update element
      run: |
        nix run .#update-nvim-plugin -- ${{ matrix.plugin }}
    - name: Update tree-sitter parsers
      if: ${{ matrix.plugin == 'nvim-treesitter' }}
      run: |
        nix run .#update-tree-sitter-grammars
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: '${{ secrets.PAT }}'
        title: 'ci: update ${{ matrix.plugin }}'
        author: GitHub <noreply@github.com>
        branch: update/${{ matrix.plugin }}
        delete-branch: true

  main:
    name: Update flake inputs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v25
      with:
        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://polarmutex.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= polarmutex.cachix.org-1:kUFH4ftZAlTrKlfFaKfdhKElKnvynBMOg77XRL2pc08=
    - name: Update flake.lock
      run: nix flake update
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: '${{ secrets.PAT }}'
        title: 'ci: bump flake'
        commit-message: |
          chore: Bump flake


          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        author: GitHub <noreply@github.com>
        branch: update/flake
        delete-branch: true
